name: Build
on:
  workflow_call
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
      - uses: actions/checkout@v3
      - name: cache dependencies
        id: cache-dependencies
        uses: actions/cache@v2
        env:
          cache-name: cache-dependencies
        with:
          path: node_modules
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
      - name: install dependencies
        if: steps.cache-dependencies.outputs.cache-hit != 'true'
        run: npm ci
      - run: npm run build:lib
      - uses: actions/upload-artifact@v2
        with:
          name: lib-build-artifacts
          path: ./dist
