name: Publish package to NPM registry
on:
  push:
    branches: ["main"]
jobs:
  build:
    uses: praveenganeshcp/simple-widgets/.github/workflows/build.yml@main
    
  test:
    needs: build
    uses: praveenganeshcp/simple-widgets/.github/workflows/test.yml@main
    
  publish:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup node environment
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          registry-url: 'https://registry.npmjs.org'
      - name: Pull cached dependencies
        id: cache-dependencies
        uses: actions/cache@v2
        env:
          cache-name: cache-dependencies
        with:
          path: node_modules
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
      - name: Install dependencies if cache hit does not happen
        if: steps.cache-dependencies.outputs.cache-hit != 'true'
        run: npm ci
      - name: Download library build artifacts
        uses: actions/download-artifact@v2
        with:
          name: lib-build-artifacts
      - name: Publish library to NPM
        run: npm run semantic-release
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}

  deploy-storybook:
    runs-on: ubuntu-latest
    needs: publish
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 
      - name: Setup node environment
        uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: Pull cached dependencies
        id: cache-dependencies
        uses: actions/cache@v2
        env:
          cache-name: cache-dependencies
        with:
          path: node_modules
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
      - name: Install dependencies if cache hit does not happen
        if: steps.cache-dependencies.outputs.cache-hit != 'true'
        run: npm ci
      - name: Deploy storybook to chromatic
        uses: chromaui/action@v1
        with:
          projectToken: ${{ secrets.CHROMATIC }}
