name: Test
on:
  workflow_call
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Setup node environment
        uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Pull cached dependencies
        id: cache-dependencies
        uses: actions/cache@v2
        env:
          cache-name: cache-dependencies
        with:
          path: node_modules
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
      - name: Install dependencies if cache hit does not happen
        if: steps.cache-dependencies.outputs.cache-hit != 'true'
        run: npm ci
      - name: Install cypress binary
        run: npx cypress install
      - name: Verify cypress
        run: npx cypress verify
      - name: Run component test
        run: npx cypress run --component --browser=chromium
